business_unit_choice = {
    None: 0,
    "": 0,
    "Network Integration Services": 1,
    "Software Company Service": 2,
    "Customer Support": 3,
    "Managed Service": 4,
    "IT Integration Service": 5,
    "Network Rollout Service": 6,
    "Managed Service & Network Assurance": 7,
    "SmartCare": 8,
    "Learning Service": 9,
    "Software & Cloud Services": 10,
    "Public Cloud Service": 11,
}
