scenario_choice = {
    "408": 1,
    "424": 2,
    "AMI": 3,
    "BCM": 4,
    "Big Data": 5,
    "BigData": 6,
    "Broadcast and Television 700M": 7,
    "BSS": 8,
    "CloudEPN": 9,
    "CloudEPN Business Solution": 10,
    "Competence Consulting and Assessment": 11,
    "Consulting": 12,
    "Core network": 13,
    "CS": 14,
    "DC Facility": 15,
    "DC Infra": 16,
    "DC-L1": 17,
    "DC-L2": 18,
    "DS": 19,
    "EI Delivery": 20,
    "Energy": 21,
    "Energy Pipeline": 22,
    "Enterprise Cloud": 23,
    "Enterprise Cloud Service": 24,
    "Enterprise Network": 25,
    "Enterprise Wireless": 26,
    "Fixed CEM": 27,
    "Fixed network": 28,
    "FTTX/OSP": 29,
    "Government Cloud Service": 30,
    "Home Broadband Business Solution": 31,
    "IBS": 32,
    "IOT": 33,
    "IOT Business Solution": 34,
    "IT Cloud Computing": 35,
    "ITO": 36,
    "KEA (Key Event Assurance)": 37,
    "KEA(Key Event Assurance)": 38,
    "KEA(Key Event ssurance)": 39,
    "Knowledge Transfer": 40,
    "LS": 41,
    "Managed Operation (CT)": 42,
    "Managed Operation (IT)": 43,
    "MBB CEM（Platform+UC）": 44,
    "MBB-RF": 45,
    "MNC": 46,
    "MS": 47,
    "MV-OSS": 48,
    "Network": 49,
    "Network Planning": 50,
    "Network Planning and Optimization Tool": 51,
    "NFV&SDN": 52,
    "NPM/NPI/SQI": 53,
    "NSF(None Sale Fulfillment)": 54,
    "NSQI": 55,
    "OSS": 56,
    "OSS&IES": 57,
    "Planning and Consulting": 58,
    "POD": 59,
    "POD (Pure Equipment)": 60,
    "Public Cloud": 61,
    "Public Cloud Service": 62,
    "Safe City": 63,
    "Smart City": 64,
    "Smart NOS": 65,
    "SOC": 66,
    "Software CS": 67,
    "Software Integration Service": 68,
    "Software ITO MS": 69,
    "Software Revenue Share": 70,
    "SPMS": 71,
    "SQM/CEA": 72,
    "Subscription and Support": 73,
    "Subway eLTE": 74,
    "Telco Cloud": 75,
    "Telco Cloud Business Solution": 76,
    "Transportation": 77,
    "Video": 78,
    "Video Business Solution": 79,
    "Video Platform": 80,
    "Wireless (Including TK)": 81,
}
if __name__ == '__main__':
    print(scenario_choice["Video Platform"])
